
package oracle.apps.empdept.view;

import oracle.apps.fnd.applcore.oaext.model.OAViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    2019-12-04T20:26:47.509
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------

public class EmployeeVOImpl extends OAViewObjectImpl {

    private static final String TABLE = "EMP";
    private static final String PKEY_ATTRIBUTE = "Empno";
    private static final String PKEY_COLUMN  = "EMPNO";

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeVOImpl() {}



}            

