package oracle.apps.empdept.view;

import java.sql.Timestamp;

import oracle.apps.fnd.applcore.oaext.model.OAViewRowImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    2020-09-21T18:46:02.154
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------

public class EmployeeVORowImpl extends OAViewRowImpl {

    public enum AttributesEnum {
        Empno,
        Ename,
        Job,
        Mgr,
        Hiredate,
        Sal,
        Comm,
        Deptno,
        Training;

        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int EMPNO = AttributesEnum.Empno.index();
    public static final int ENAME = AttributesEnum.Ename.index();
    public static final int JOB = AttributesEnum.Job.index();
    public static final int MGR = AttributesEnum.Mgr.index();
    public static final int HIREDATE = AttributesEnum.Hiredate.index();
    public static final int SAL = AttributesEnum.Sal.index();
    public static final int COMM = AttributesEnum.Comm.index();
    public static final int DEPTNO = AttributesEnum.Deptno.index();
    public static final int TRAINING = AttributesEnum.Training.index();

    public static final String VC_FindByEmpnoVC = "FindByEmpnoVC";

    public static final String VAR_Empno = "Empno";

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeVORowImpl() {
    }

    /**
     * Gets the attribute value for EMPNO using the alias name Empno.
     * @return the EMPNO
     */
    public Integer getEmpno() {
        return (Integer) getAttributeInternal(EMPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPNO using the alias name Empno.
     * @param value value to set the EMPNO
     */
    public void setEmpno(Integer value) {
        setAttributeInternal(EMPNO, value);
    }

    /**
     * Gets the attribute value for ENAME using the alias name Ename.
     * @return the ENAME
     */
    public String getEname() {
        return (String) getAttributeInternal(ENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for ENAME using the alias name Ename.
     * @param value value to set the ENAME
     */
    public void setEname(String value) {
        setAttributeInternal(ENAME, value);
    }

    /**
     * Gets the attribute value for JOB using the alias name Job.
     * @return the JOB
     */
    public String getJob() {
        return (String) getAttributeInternal(JOB);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB using the alias name Job.
     * @param value value to set the JOB
     */
    public void setJob(String value) {
        setAttributeInternal(JOB, value);
    }

    /**
     * Gets the attribute value for MGR using the alias name Mgr.
     * @return the MGR
     */
    public String getMgr() {
        return (String) getAttributeInternal(MGR);
    }

    /**
     * Sets <code>value</code> as attribute value for MGR using the alias name Mgr.
     * @param value value to set the MGR
     */
    public void setMgr(String value) {
        setAttributeInternal(MGR, value);
    }

    /**
     * Gets the attribute value for HIREDATE using the alias name Hiredate.
     * @return the HIREDATE
     */
    public Timestamp getHiredate() {
        return (Timestamp) getAttributeInternal(HIREDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for HIREDATE using the alias name Hiredate.
     * @param value value to set the HIREDATE
     */
    public void setHiredate(Timestamp value) {
        setAttributeInternal(HIREDATE, value);
    }

    /**
     * Gets the attribute value for SAL using the alias name Sal.
     * @return the SAL
     */
    public Float getSal() {
        return (Float) getAttributeInternal(SAL);
    }

    /**
     * Sets <code>value</code> as attribute value for SAL using the alias name Sal.
     * @param value value to set the SAL
     */
    public void setSal(Float value) {
        setAttributeInternal(SAL, value);
    }

    /**
     * Gets the attribute value for COMM using the alias name Comm.
     * @return the COMM
     */
    public Float getComm() {
        return (Float) getAttributeInternal(COMM);
    }

    /**
     * Sets <code>value</code> as attribute value for COMM using the alias name Comm.
     * @param value value to set the COMM
     */
    public void setComm(Float value) {
        setAttributeInternal(COMM, value);
    }

    /**
     * Gets the attribute value for DEPTNO using the alias name Deptno.
     * @return the DEPTNO
     */
    public Integer getDeptno() {
        return (Integer) getAttributeInternal(DEPTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPTNO using the alias name Deptno.
     * @param value value to set the DEPTNO
     */
    public void setDeptno(Integer value) {
        setAttributeInternal(DEPTNO, value);
    }

    /**
     * Gets the attribute value for TRAINING using the alias name Training.
     * @return the TRAINING
     */
    public Integer getTraining() {
        return (Integer) getAttributeInternal(TRAINING);
    }

    /**
     * Sets <code>value</code> as attribute value for TRAINING using the alias name Training.
     * @param value value to set the TRAINING
     */
    public void setTraining(Integer value) {
        setAttributeInternal(TRAINING, value);
    }


}
